version: '3.5'

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile-dev
    environment:
      - API_KEY=api-key-here
      - DB_HOST=postgres
    ports:
      - '3000:3000'
    volumes:
      - ../backend/src:/usr/app/src
    depends_on:
      - postgres

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile-dev
    ports:
      - '8080:8080'
    volumes:
      - ../frontend/src:/usr/app/src
      - ../frontend/public:/usr/app/public
    depends_on:
      - backend

  postgres:
    image: postgres:15-alpine
    volumes:
      - postgres-db:/data/postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres

volumes:
  postgres-db:
